/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        //ANSI 코드 입력
        String resetAnsi = "\033[0m";   // Text Reset
        String redAnsi = "\033[31m"; // Red Bold
        String boldAnsi = "\033[1m";

        //초기화면 변수할당
        String line = "--------------------------";
        String appTitle = "[팀 프로젝트 관리 시스템]";
        String[] menus = new String[]{
                "회원",
                "팀",
                "프로젝트",
                "게시판",
                "도움말",
                "종료"};

        //초기화면 출력
        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + appTitle + resetAnsi);
        System.out.println();
        for (int i = 0; i < menus.length; i++) {
            if (menus[i].equals("종료")) {
                System.out.printf("%s%d. %s%s\n", (redAnsi + boldAnsi), (i + 1), menus[i], resetAnsi);
            } else System.out.printf("%d. %s\n", i + 1, menus[i]);
        }
        System.out.println(boldAnsi + line + resetAnsi);
        Scanner keyboardScanner = new Scanner(System.in);

        // 메뉴 선택하기
        int menuNo;
        while (true) {
            try {
                System.out.print("> ");
                menuNo = keyboardScanner.nextInt();

                if (menuNo >= 1 && menuNo <= menus.length) {
                    if (menus[menuNo - 1].equals("종료")) {
                        break;
                    }
                    System.out.println(menus[menuNo - 1]);
                } else {
                    System.out.println("유효한 메뉴 번호가 아닙니다.");
                }
            } catch(InputMismatchException ex) {
                System.out.println("숫자로 메뉴번호를 입력하세요");
                keyboardScanner.next();
            }
        }
        System.out.println("종료합니다.");
        keyboardScanner.close();
    }
}

