/*
 * This source file was generated by the Gradle 'init' task
 */
package myApp;

import myApp.Decorator.Milk;
import myApp.Decorator.Mocha;
import myApp.Decorator.Whip;
import myApp.concreteComponet.DarkRoast;
import myApp.concreteComponet.Espresso;

public class App {
    public static void main(String[] args) {
        Beverage espresso = new Espresso();
        System.out.println(espresso.cost());
        System.out.println(espresso.getDescription());

        Beverage cafeMocha = new DarkRoast();
        cafeMocha = new Milk(cafeMocha);
        cafeMocha = new Mocha(cafeMocha);
        cafeMocha = new Whip(cafeMocha);

        System.out.println(cafeMocha.cost());
        System.out.println(cafeMocha.getDescription());
    }
}
